
title: Muhammad Raihan
description: website Raihan
url: 'https://mraihanads.github.io'  # URL utama situs
baseurl: ''  

author:
  name: Muhammad Raihan
  email: mraihanads@gmail.com

# Permalink untuk URL posting
permalink: /:year/:month/:day/:title/

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
